### ISSUE TITLE
Invite to Firebase

### ISSUE THREAD

**Issue by ed6767** [MasterOfTheTiger/bible-electron#13]
Please leave your email here so I can invite you to the Firebase area so we can manage the backend.

Edit by MasterOfTheTiger: removed link

**Comment by MasterOfTheTiger** [comment]
What if someone random sees this and adds theirs?

**Comment by edxtech** [comment]
I will know :p

**Comment by MasterOfTheTiger** [comment]
@edxtech I don't want to use Firebase. It is non-free software. Worse yet, it is run by Google. However, I will give you a chance. Why do you want to use Firebase?

**Comment by hellounicorns2** [comment]
I’m not willing to give my email out as it contains my real name, sorry.

**Comment by MasterOfTheTiger** [comment]
@hellounicorns2 I don't use my real name on the internet at all (with a couple exceptions). I use a fake name for my email. Also, I don't think that you necessarily require access to Firebase at all. So you are fine if you don't give out an email.

**Comment by hellounicorns2** [comment]
Ok...

**Comment by amazinigmech2418** [comment]
I don't want to give out my email since it gives out my name.

**Comment by MasterOfTheTiger** [comment]
Okay @amazinigmech2418. I don’t care if you want to have access to it or not. I understand your concerns (though personally I don’t use my real name at all on the web).
